# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
