# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_hello_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hello',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 30, 18, 51, 50, 293131, tzinfo=utc), verbose_name=datetime.datetime(2016, 7, 30, 20, 51, 31, 859455)),
            preserve_default=False,
        ),
    ]
