# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:52
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160730_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 30, 20, 52, 48, 679909)),
        ),
    ]
