# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20160730_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 30, 21, 0, 52, 8483)),
        ),
    ]
