# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:03
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20160730_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='title',
            field=models.CharField(default='- empty title -', max_length=100),
        ),
        migrations.AlterField(
            model_name='hello',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 30, 21, 3, 24, 166230)),
        ),
    ]
