# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 08:16
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20160730_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='hello',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 10, 16, 43, 829984)),
        ),
        migrations.AlterField(
            model_name='hello',
            name='test_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 10, 16, 43, 830076)),
        ),
    ]
