# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20160731_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hello',
            old_name='test_date',
            new_name='updated_at',
        ),
    ]
