# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20160731_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
