# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20160731_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 12, 10, 0, 989163, tzinfo=utc), verbose_name=datetime.datetime(2016, 7, 31, 12, 9, 43, 965362, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hello',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 12, 10, 7, 413247, tzinfo=utc), verbose_name=datetime.datetime(2016, 7, 31, 12, 9, 43, 965362, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
