# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20160731_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 12, 12, 18, 529701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hello',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 12, 12, 18, 529701, tzinfo=utc)),
        ),
    ]
