# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20160731_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='published',
        ),
        migrations.RemoveField(
            model_name='example',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hello',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hello',
            name='published',
        ),
        migrations.RemoveField(
            model_name='hello',
            name='updated_at',
        ),
    ]
